### ISSUE TITLE
read.runrec(), process.runrec(): 'run1' disappears from each table under current PsN

### ISSUE THREAD

**Issue by bergsmat** [qPharmetra/qpToolkit#44]
Per Marita (buglist).  These are confirmed working under PsN 4.2.0.

**Comment by bergsmat** [comment]
Need to identify current PsN and test cases that break existing code.  Re-run existing models under NONMEM 7.4 / PsN 4.8?

**Comment by krinaj** [comment]
Just tested; no issues identified in read.runrec() or process.runrec(). 

Actually, it seems like an user error with PsN runrecord command, i.e. when runrecord file is crated using PsN command, one needs to specify -from=0 in order to have run1 in the .txt file. If -from=1 is used then run1 is not included.

**Comment by bergsmat** [comment]
Let's consider this closed for now, and re-open as necessary.
